name: "Prerelease"

# Trigger the create release workflow
on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        python: ['3.9', '3.10', '3.11', '3.12']

    steps:
      - uses: actions/checkout@v3
      - name: Use Python ${{ matrix.python }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python }}
      - name: Install dependencies
        run: |
            python -m pip install --upgrade pip
            pip install build
      - name: Build package
        run: python -m build
      - uses: actions/upload-artifact@v2
        with:
          path: dist/*
          if-no-files-found: error
